package com.paperworld.flash.api.multiplayer 
{
	import com.paperworld.flash.multiplayer.data.State;
	import com.paperworld.flash.util.input.IUserInput;
	import com.paperworld.flash.util.input.Input;	

	/**
	 * @author Trevor
	 */
	public interface ISynchronisedAvatar
	{
		function set userInput(value : IUserInput) : void;
		
		function set syncManager(value:ISyncManager):void;

		function get object() : ISynchronisedObject;

		function set object(value : ISynchronisedObject) : void;

		/**
		 * The unique id for this avatar - generated by the server.
		 */
		function get id() : String;

		/**
		 * @private
		 */
		function set id(value : String) : void;

		function get time() : int;

		function set time(time : int) : void;

		function get input() : Input;

		function set input(input : Input) : void;

		function get state() : State;

		function set state(state : State) : void;

		function get replaying() : Boolean;

		function set replaying(replaying : Boolean) : void;

		function get tightness() : Number;

		function set tightness(tightness : Number) : void;

		function snap(state : State) : void;

		function update() : void;
		
		function destroy():void;
	}
}
